# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = ExpTrc
DESTDIR = ../x64/Release
CONFIG += release
DEFINES += $(Qt_DEFINES_) \"$(INHERIT)\" RELEASE
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
QT += network
include(ExpTrc.pri)
